Error: In HTML, <tr> cannot be a child of <table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.
This will cause a hydration error.

  ...
    <link>
    <script>
    <script>
    <script>
    <script>
    <script>
    <script>
    <ClientSegmentRoot Component={function RootLayout} slots={{...}} params={{}}>
      <RootLayout params={Promise}>
        <html lang="es">
          <body className="bg-gray-10...">
            <header>
            <main className={"flex fle..."}>
              <motion.h1>
              <MainButtons publico={1} esAdmin={false} esProfesor={true} onSelect={function onSelect}>
                <div className="flex flex-...">
                  <div>
                  <ReportesModal onClose={function onClose}>
                    <div className="p-6 rounde...">
                      <div className="relative f...">
                        <button>
                        <h2>
                        <div>
                        <div className="space-y-4">
                          <div className="border bor...">
                            <div>
                            <div className="p-4 space-y-3">
                              <table>
                              <div className="overflow-x...">
>                               <table className="min-w-full border text-xs mt-3">
                                  <thead>
>                                 <tr className="bg-gray-100 text-[#990000] font-medium">
                                  ...
                          ...
              ...
            ...

    at createUnhandledError (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_523921._.js:689:49)
    at handleClientError (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_523921._.js:856:56)
    at console.error (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_523921._.js:991:56)
    at validateDOMNesting (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:1804:212)
    at completeWork (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7273:25)
    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:631:20)
    at completeUnitOfWork (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8020:23)
    at performUnitOfWork (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7957:28)
    at workLoopSync (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7847:40)
    at renderRootSync (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7830:13)
    at performWorkOnRoot (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7565:211)
    at performSyncWorkOnRoot (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8402:9)
    at flushSyncWorkAcrossRoots_impl (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8326:245)
    at processRootScheduleInMicrotask (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8343:9)
    at http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8413:126
