[
    {
        "id": 450,
        "NombreCurso": "Profesores Prub",
        "Valor": null,
        "Publico": "Profesores",
        "Periodo": "2025-2",
        "Inicio": "2025-04-30",
        "Fin": "2025-05-10",
        "InicioInscr": null,
        "FinInscr": null,
        "Horas": 5,
        "CupoMax": 20,
        "Lugar": "bloque",
        "LunesIni": "10:51",
        "LunesFin": "23:51",
        "MartesIni": null,
        "MartesFin": null,
        "MiercolesIni": null,
        "MiercolesFin": null,
        "JuevesIni": null,
        "JuevesFin": null,
        "ViernesIni": null,
        "ViernesFin": null,
        "SabadoIni": null,
        "SabadoFin": null,
        "DomingoIni": null,
        "DomingoFin": null,
        "Linea": "Unidad de gestión externa",
        "Estado": "Activo",
        "Modalidad": "Presencial",
        "Unidad": "Unidad de Proyectos                     ",
        "Profesor": 1000034366,
        "SegundoPro": "SUAREZ ESPINOSA JOHAN SMITH",
        "Proexterno": null,
        "Descripcion": null,
        "IdTipoCurso": "Cursos BU y otros",
        "NombreProfesor": "RODRIGUEZ REY WENDY SOFIA",
        "Inscritos": "[{\"id\":1602,\"idCur\":450,\"docInscr\":1000034366,\"est\":true,\"fecreg\":\"2025-05-05\"}]"
    },
    {
